//Ajax call to query for static ingredient information and static equipment information to be displayed as a listbox
$.ajax({
    type: "GET",
    url: 'drinkInfo.php',
    dataType: "json",
    success: function(data){
      console.log(data);
      var step_amt = 0; //Number of steps added by the user when they to upload a new drink
      var equip_amt = 0; //Number of equipment added by the user when they try to upload a new drink
      var ingred_amt = 0; //Number of ingredients added by the user when they try to upload a new drink

      //Button listener that will insert a new directions input box for a drink
      document.getElementById("addstep").addEventListener("click", function(){
        step_amt++;

        //Append a new input textbox for drink directions to the DIV
        document.getElementById("removeStep").style.display = "block";
        var steps = document.getElementById("Steps_Div");
        var stepNew = document.createElement("input");
        stepNew.setAttribute("type", "text");
        stepNew.setAttribute("id", "Steps");
        stepNew.setAttribute("name", "Steps[]");
        stepNew.setAttribute("placeholder", "Step " + step_amt);
        stepNew.required = true;
        steps.appendChild(stepNew);
      });

      //Button listener that will remove last created step textbox
      document.getElementById("removeStep").addEventListener("click", function(){
        remove = document.getElementById("Steps_Div").querySelectorAll("#Steps");
        remove[step_amt-1].parentNode.removeChild(remove[step_amt-1]);
        step_amt--;
        if(step_amt == 0){
          document.getElementById("removeStep").style.display = "none";
        }
      });

      //Button listener that will add a new ingredient input textfield to add ingredient info
      document.getElementById("addIngr").addEventListener("click", function(){
        ingred_amt++

        //Get looping max from the number of queries generated by the AJAX request
        if(data[1].name == 1){
          var max = data[1].name;
        }
        else{
          max = data[1].name - 1;
        }


        document.getElementById("removeIngr").style.display = "block";


        var steps = document.getElementById("Ingredients_Div");

        //Create a select listbox that will display the static ingredients currently in the DB that the user can choose from
        var type = document.createElement("select");
        type.setAttribute("id", "Ingredients");
        type.setAttribute("name", "Ingredients[]");

        //Loop through queries and insert a new option with the ingredient name, type and unit
        for(var i = 0; i < max; i++){
          optionAlch = document.createElement("option");
          optionAlch.setAttribute("value", i+1);
          alcohol = document.createTextNode(data[1][i] + " (" + data[2][i] + "/" + data[3][i] + ")");
          optionAlch.appendChild(alcohol);
          type.appendChild(optionAlch);
        }

        newline = document.createElement("br");
        newline.setAttribute("id", "nline");
        steps.appendChild(type);

        //Creates a new text input box where the user can enter the amount of ingredients
        amount = document.createElement("input");
        amount.setAttribute("type", "number");
        amount.setAttribute("id", "Amount");
        amount.setAttribute("name", "Amount[]");
        amount.setAttribute("placeholder", "Amount");
        amount.required = true;
        steps.appendChild(amount);
        steps.appendChild(newline);
      });

      //Button listener that will remove the last created input text field for the ingredients input
      document.getElementById("removeIngr").addEventListener("click", function(){
        removeIng = document.getElementById("Ingredients_Div").querySelectorAll("#Ingredients");
        removeIng[ingred_amt-1].parentNode.removeChild(removeIng[ingred_amt-1]);

        removeIng = document.getElementById("Ingredients_Div").querySelectorAll("#Amount");
        removeIng[ingred_amt-1].parentNode.removeChild(removeIng[ingred_amt-1]);

        removeIng = document.getElementById("Ingredients_Div").querySelectorAll("#nline");
        removeIng[ingred_amt-1].parentNode.removeChild(removeIng[ingred_amt-1]);

        ingred_amt--;
        if(ingred_amt == 0){
          document.getElementById("removeIngr").style.display = "none";
        }
      });

      //Button listener that will add a new equipment listbox that contains all the static equipment currently in the DB
      document.getElementById("addEquip").addEventListener("click", function(){
        equip_amt++;
        document.getElementById("removeEquip").style.display = "block";

        //Get the number of queries generated from the AJAX request for the equipment tuples
        if(data[0].equipment == 1){
          var max = data[0].equipment;
        }
        else{
          max = data[0].equipment - 1;
        }

        var steps = document.getElementById("Equipment_Div");

        //Creates a new listbox where the user can pick one of the equipment that is currently in the DB
        var type = document.createElement("select");
        type.setAttribute("id", "Equipment");
        type.setAttribute("name", "Equipment[]");

        //Loop through the equipment queries and display each tuple as a new option in the listbox
        for(var i = 0; i < max; i++){
          optionEquip = document.createElement("option");
          optionEquip.setAttribute("value", data[0][i]);
          equipment = document.createTextNode(data[0][i]);
          optionEquip.appendChild(equipment);
          type.appendChild(optionEquip);
        }

        newline = document.createElement("br");
        newline.setAttribute("id", "nline");
        steps.appendChild(type);
        steps.appendChild(newline);
      });

      //Button listener that will remove the last created equipment listbox
      document.getElementById("removeEquip").addEventListener("click", function(){
        removeEqu = document.getElementById("Equipment_Div").querySelectorAll("#Equipment");
        removeEqu[equip_amt-1].parentNode.removeChild(removeEqu[equip_amt-1]);

        removeEqu = document.getElementById("Equipment_Div").querySelectorAll("#nline");
        removeEqu[equip_amt-1].parentNode.removeChild(removeEqu[equip_amt-1]);

        equip_amt--;
        if(equip_amt == 0){
          document.getElementById("removeEquip").style.display = "none";
        }
      });


    }
});

/*
  Function: signup()
  Description: If the user wants to create a new account then they will be redirected to the signup page
*/
function signup(){
  location.href = 'sign-up.php';
}

/*
  Function: login()
  Description: If the user wants to login with an existing account then they will be redirected to the log in page
*/
function login(){
  location.href = 'log-in.php';
}
